### ISSUE TITLE
Printing loses all formatting

### ISSUE THREAD

**Issue by lb42** [TEIC/CETEIcean#12]
A file which looks fine on screen doesn't get formatted properly when sent to the printer, using "Print" command in Firefox. Is it meant to work? If not, why not?

**Comment by hcayless** [comment]
This seems better in the current version of Firefox, but it does still have problems. Setting print styles for custom elements seems not to work. Perhaps it will when custom elements are fully implemented.

**Comment by hcayless** [comment]
Actually, with some experimentation, I think this is resolved, but will require some care and attention to print vs. screen CSS to work properly.

**Comment by lb42** [comment]
Could you maybe post an example of a file where it does work? What experimentation have you carried out?

**Comment by hcayless** [comment]
I noticed the examples all had `@media="screen"` on their stylesheet links. Removing that fixes it for me. You could also keep it and add a separate print stylesheet. Anyway, turns out it's entirely expected behavior. It's just that there aren't any default print styles for custom elements (unsurprisingly). I've updated all the examples at http://teic.github.io/CETEIcean/ and they should print fine now.
