### ISSUE TITLE
Multiple @target value not handled properly

### ISSUE THREAD

**Issue by lb42** [TEIC/CETEIcean#15]
The @target attribute on ptr or ref can supply multiple pointers: e.g. `<ref target="#foo #bar"/>` This is plausibly handled by the default TEI to HTML conversion (you get two links in the HTML) but CETEIcean produces one link with an invalid URI (the concatenation of the two URIs supplied in the TEI source), thus resulting in a 404.

**Comment by hcayless** [comment]
The proper solution to this would be to write a custom behavior function that supports multiple targets. I'm not really sure what the ideal output should be. Multiple links? A dropdown with links?

I'm not sure the base version of CETEIcean should support this, though I could be persuaded otherwise, I'm sure.

**Comment by lb42** [comment]
It would be better to choose arbitrarily one of the available target values than to generate an invalid output, surely? Or just do what the default TEItoHTML conversion does and generate multiple links.

**Comment by hcayless** [comment]
Multiple `@target`s will have just the first URL displayed. This behavior can, of course, be overwritten.
