### ISSUE TITLE
How to use CETEIcean server-side (if possible)?

### ISSUE THREAD

**Issue by kibin-app** [TEIC/CETEIcean#56]
Hello there,

first of all, a huge thank you for this library, such a great tool. I assume that all those who use it find it invaluable. 👍 

**My question**
I would love to use CETEIcean in a SSR (server-side rendering) environment ([Next.js](https://nextjs.org/)). I assumed that custom elements require the `window` object, thus SSR not being an option. 

But this part of the docs has me wondering if this is actually possible:
> To turn this behaviour off, particularly when using CETEIcean for Server Side Rendering, you can set the ignoreFragmentId option to true:

Could anyone elaborate on this? Does anyone have an example of CETEIcean + SSR in the wild?

When I try to use CETEIcean in SSR, I get the (not surprising) error that `window` is not defined. I did not set any behaviours, and also tried setting `ignoreFragmentId: true` as suggested in the docs:

For those interested: this is my custom hook using[ tanstack-query](https://tanstack.com/query/v4) (which should not be an issue here), which gets called in NodeJS:
```js
import { useQuery } from '@tanstack/react-query'
import CETEI from '@/library/CETEI'

const fetchTeiText = async (slug: string) => {
  const ct = new CETEI({ ignoreFragmentId: true })

  return await ct.getHTML5(`data/tei/${slug}.xml`)
}

const useTeiText = (slug: string) => {
  return useQuery(['tei-text', slug], () => fetchTeiText(slug))
}

export { useTeiText, fetchTeiText }
```

I tried looking into tweaking the actual library, but that might not be a good idea due to my lack of knowledge regarding custom elements and CETEIcean's internals.

Any feedback is highly appreciated

**Comment by raffazizzi** [comment]
Hello @kibin-app thanks for your question! I think the Server Side Rendering comment you quoted is somewhat misleading because in order to define the Custom Elements, `window` needs to be available (see [define()](https://github.com/TEIC/CETEIcean/blob/56aa4f8c75e225d6522eee0572f66f038f904cb8/tutorial_es/js/CETEI.js#L843)). However, that process only needs to happen on the client side.

In order to implement SSR, it's helpful to think of CETEIcean as performing three main tasks:
* transforming the TEI source data into `tei-` prefixed elements with the addition of some helpful `data-` attributes to avoid data loss. This is handled by [makeHTML5()](https://github.com/TEIC/CETEIcean/blob/56aa4f8c75e225d6522eee0572f66f038f904cb8/tutorial_es/js/CETEI.js#L520)
* register the transformed elements as Custom Elements, handled by [define()](https://github.com/TEIC/CETEIcean/blob/56aa4f8c75e225d6522eee0572f66f038f904cb8/tutorial_es/js/CETEI.js#L843)
* apply behaviors

The last two tasks need to happen in the client and will require `window`. But the first task can be done server side. The [example XSLT](https://github.com/TEIC/CETEIcean/blob/56aa4f8c75e225d6522eee0572f66f038f904cb8/xslt/make-CETEIcean.xsl) included in the repository, for example, takes care of that. In short, you would have to implement that code on your own.

There is an example of this in the wild: I adapted CETEIcean code to work with [Gatsby](https://www.gatsbyjs.com/) specifically to take advantage of SSR, but also for being able to use React components instead of behaviors. You can find the code and some docs at https://github.com/raffazizzi/gatsby-transformer-ceteicean . It performs the required transformation step I mentioned above and allows users to queue further transformations if they need them. Feel free to open issues there if you have questions about that code. 

This transformer has a companion Gatsby "theme" that performs the other two steps on the client: register the Custom Elements and route React components to handle behaviors. The code is here: https://github.com/raffazizzi/gatsby-theme-ceteicean

I hope this helps!

**Comment by kibin-app** [comment]
Thank you for the swift reply and the example! That does help a lot indeed. I'll debate with myself if it's worth the extra mile or just leave it on the client side.
